runtime: python39
entrypoint: streamlit run main.py --server.port $PORT --server.headless true
instance_class: F1

automatic_scaling:
  max_instances: 1

handlers:
- url: /.*
  script: auto
